# Generated by Django 2.1.7 on 2019-04-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourthsection',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='logo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='secondsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='slider',
            name='screen',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
