# Generated by Django 2.1.7 on 2019-04-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0002_auto_20190430_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsectiion',
            name='email',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
