# Generated by Django 2.1.7 on 2019-04-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0003_contactsectiion_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsectiion',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
