# Generated by Django 2.1.7 on 2019-05-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0004_contactsectiion_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Про сайт'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='hot_key',
            field=models.CharField(help_text='Напишіть головний заголовок вкладки', max_length=150, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='title',
            field=models.CharField(help_text='Напишіть головний заголовок вкладки', max_length=80, verbose_name='Заголовок сайту'),
        ),
    ]
