# Generated by Django 2.1.7 on 2019-05-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0006_auto_20190502_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Information',
            new_name='Meta_tag',
        ),
    ]
