# Generated by Django 2.1.7 on 2019-05-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0007_auto_20190502_1931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meta_tag',
            new_name='MetaTag',
        ),
    ]
