# Generated by Django 2.1.7 on 2019-05-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0008_auto_20190502_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='screen2',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='slider',
            name='screen3',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='slider',
            name='screen4',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
