# Generated by Django 2.1.7 on 2019-05-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0009_auto_20190503_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='screen',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
