# Generated by Django 2.1.7 on 2019-05-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0011_auto_20190503_1756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='lit',
        ),
    ]
