# Generated by Django 2.1.7 on 2019-05-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0013_auto_20190503_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='add_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
