# Generated by Django 2.1.7 on 2019-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0014_auto_20190503_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.ImageField(blank=True, null=True, upload_to='')),
                ('screen2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('screen3', models.ImageField(blank=True, null=True, upload_to='img')),
                ('screen4', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
