# Generated by Django 2.1.7 on 2019-05-06 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0016_slider_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstsection',
            old_name='paragraph_fr',
            new_name='paragraphFR',
        ),
    ]
