# Generated by Django 2.1.7 on 2019-05-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0017_auto_20190507_0239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='ServisList',
        ),
        migrations.RemoveField(
            model_name='firstsection',
            name='paragraphFR',
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='paragraph',
            field=models.CharField(max_length=500),
        ),
    ]
