# Generated by Django 2.1.7 on 2019-05-07 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0018_auto_20190507_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servislist',
            old_name='item_ff',
            new_name='itemList',
        ),
        migrations.RemoveField(
            model_name='servislist',
            name='item_fr',
        ),
        migrations.RemoveField(
            model_name='servislist',
            name='item_ft',
        ),
        migrations.RemoveField(
            model_name='servislist',
            name='item_sk',
        ),
        migrations.RemoveField(
            model_name='servislist',
            name='item_sv',
        ),
        migrations.RemoveField(
            model_name='servislist',
            name='item_sx',
        ),
        migrations.RemoveField(
            model_name='servislist',
            name='item_th',
        ),
    ]
