# Generated by Django 2.1.7 on 2019-05-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0019_auto_20190507_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='screen2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='screen3',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='screen4',
        ),
    ]
