# Generated by Django 2.1.7 on 2019-05-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0020_auto_20190509_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstsection',
            name='name',
        ),
    ]
