# Generated by Django 2.1.7 on 2019-05-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0021_remove_firstsection_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSectiion',
        ),
        migrations.DeleteModel(
            name='FirstSection',
        ),
        migrations.DeleteModel(
            name='FourthSection',
        ),
        migrations.DeleteModel(
            name='logo',
        ),
        migrations.DeleteModel(
            name='MetaTag',
        ),
        migrations.DeleteModel(
            name='SecondSection',
        ),
        migrations.DeleteModel(
            name='ServisList',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
