# Generated by Django 2.1.7 on 2019-05-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('new_wings', '0022_auto_20190513_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Повне імя')),
                ('age', models.CharField(max_length=50, verbose_name='Вік')),
                ('city', models.CharField(max_length=100, verbose_name='Місце проживання ')),
                ('profesion', models.CharField(max_length=100, verbose_name='Професія')),
                ('problem', models.CharField(max_length=220, verbose_name='Проблема що торбує')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scren', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
    ]
