# Generated by Django 2.1.7 on 2019-05-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0023_personaldate_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='scren',
        ),
        migrations.AddField(
            model_name='slider',
            name='screen',
            field=models.ImageField(blank=True, null=True, upload_to='new_wings/image'),
        ),
    ]
