# Generated by Django 2.1.7 on 2019-05-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0025_auto_20190513_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldate',
            name='diseases',
            field=models.TextField(max_length=500, null=True, verbose_name='Травми,операції хронологічні захворювання'),
        ),
        migrations.AddField(
            model_name='personaldate',
            name='reabilitations_type',
            field=models.CharField(blank=True, max_length=220, verbose_name='Нещодавно проведена реабілітація'),
        ),
    ]
