# Generated by Django 2.1.7 on 2019-05-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0026_auto_20190514_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='PersonalDate',
        ),
        migrations.AddField(
            model_name='slider',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
