# Generated by Django 2.1.7 on 2019-05-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0027_auto_20190521_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
