# Generated by Django 2.1.7 on 2019-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0029_contact_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='name',
        ),
        migrations.AlterField(
            model_name='information',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Інформація'),
        ),
    ]
