# Generated by Django 2.1.7 on 2019-05-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0030_auto_20190521_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
