# Generated by Django 2.1.7 on 2019-05-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0031_auto_20190521_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reabilitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
    ]
