# Generated by Django 2.1.7 on 2019-05-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0032_reabilitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reabil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
        migrations.DeleteModel(
            name='Reabilitation',
        ),
    ]
