# Generated by Django 2.1.7 on 2019-05-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0034_donate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to='image')),
                ('account', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Donate',
        ),
    ]
