# Generated by Django 2.1.7 on 2019-05-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0035_auto_20190522_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='account',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='icon',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
