# Generated by Django 2.1.7 on 2019-05-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0036_auto_20190522_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('images', models.ImageField(null=True, upload_to='image/')),
                ('text', models.TextField(verbose_name='Опис')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('description', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=50, verbose_name='Ключові слова')),
            ],
        ),
    ]
