# Generated by Django 2.1.7 on 2019-05-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0037_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
