# Generated by Django 2.1.7 on 2019-05-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0038_auto_20190525_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='description',
        ),
    ]
