# Generated by Django 2.1.7 on 2019-05-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0040_suportform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuportForm',
            new_name='Suport',
        ),
    ]
