# Generated by Django 2.1.7 on 2019-05-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0041_auto_20190530_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suport',
            name='age',
            field=models.CharField(max_length=50, verbose_name='ваш вік'),
        ),
        migrations.AlterField(
            model_name='suport',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name="Прізвище Ім'я По батькові"),
        ),
        migrations.AlterField(
            model_name='suport',
            name='trade',
            field=models.CharField(max_length=150, verbose_name=''),
        ),
    ]
