# Generated by Django 2.1.7 on 2019-06-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0042_auto_20190530_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suport',
            name='trade',
        ),
        migrations.AlterField(
            model_name='suport',
            name='live_through',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='suport',
            name='problem',
            field=models.TextField(verbose_name='Проблема що торбує'),
        ),
    ]
