# Generated by Django 2.1.7 on 2019-06-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0043_auto_20190601_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='suport',
            name='city',
            field=models.TextField(default='SOME STRING', max_length=200, verbose_name='Місце проживання'),
        ),
    ]
