# Generated by Django 2.1.7 on 2019-06-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0044_suport_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suport',
            name='real_problem',
        ),
        migrations.AddField(
            model_name='suport',
            name='reabil_type',
            field=models.CharField(default='SOME STRING', max_length=100, verbose_name='Вид реабілітації'),
        ),
        migrations.AlterField(
            model_name='suport',
            name='exemption',
            field=models.CharField(max_length=150, verbose_name='Вид реабілітації'),
        ),
        migrations.AlterField(
            model_name='suport',
            name='live_through',
            field=models.TextField(max_length=200, verbose_name='Перенесині травми,операції а також наяві захворювання:  '),
        ),
    ]
