# Generated by Django 2.1.7 on 2019-06-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0047_auto_20190603_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suport',
            name='age',
            field=models.IntegerField(verbose_name='ваш вік'),
        ),
    ]
