# Generated by Django 2.1.7 on 2019-06-03 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0048_auto_20190603_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suport',
            name='age',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='ваш вік'),
        ),
    ]
