# Generated by Django 2.1.7 on 2019-06-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0051_auto_20190603_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suport',
            name='exemption',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Наявність пільг'),
        ),
    ]
