# Generated by Django 2.1.7 on 2019-06-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_wings', '0052_auto_20190603_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suport',
            name='exemption',
            field=models.BooleanField(verbose_name='Наявність пільг'),
        ),
    ]
